
SOURCES = main.cpp

upy++ : $(SOURCES)
	g++ -I /usr/include/python2.7 -o upy++ $(SOURCES)

apy++ : $(SOURCES)
	g++ -I /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/ $(SOURCES) -o apy++
